######################################################################
# Automatically generated by qmake (3.0) Fri Jul 15 21:24:03 2016
######################################################################

TEMPLATE = app
TARGET = astraea
INCLUDEPATH += .

QT += widgets

MOC_DIR = build
OBJECTS_DIR = build

# Input
HEADERS += src/editor.hpp
SOURCES += src/editor.cpp src/entry.cpp src/property.cpp src/main.cpp
